package fr.loicknuchel.safeql.testingutils.database

import fr.loicknuchel.safeql.Table.SqlTable

/**
 * Hello
 *
 * Class generated by fr.loicknuchel.safeql.gen.writer.ScalaWriter
 */
object Tables {
  val CATEGORIES: tables.CATEGORIES = tables.CATEGORIES.table
  val FEATURED: tables.FEATURED = tables.FEATURED.table
  val KINDS: tables.KINDS = tables.KINDS.table
  val POSTS: tables.POSTS = tables.POSTS.table
  val USERS: tables.USERS = tables.USERS.table

  def getTables: List[SqlTable] = List(CATEGORIES, FEATURED, KINDS, POSTS, USERS)
}
